ALTER TABLE CUSTOMERS
    ADD COLUMN EMAIL VARCHAR(45) NOT NULL,
    ADD COLUMN PHONENUMBER VARCHAR(20) NOT NULL;

ALTER TABLE ORDERS
    ADD COLUMN AMOUNT INT(4) UNSIGNED NOT NULL,
    ADD COLUMN DESCRIPTION VARCHAR(45) NOT NULL,
    MODIFY COLUMN ORDER_DATE DATE;